const lockers = {
  state: {
    lockers: [
      {
        id: 0,
        size: "xs",
        locked: false,
        occupied: true,
        selected: false,
      },
      {
        id: 1,
        size: "xs",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 2,
        size: "xs",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 3,
        size: "xs",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 4,
        size: "xs",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 5,
        size: "xs",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 6,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 7,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 8,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 9,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 10,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 11,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 12,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 13,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 14,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 15,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 16,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 17,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 18,
        size: "sm",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 19,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 20,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 21,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 22,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 23,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 24,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 25,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 26,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 27,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 28,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 29,
        size: "md",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 30,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 31,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 32,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 33,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 34,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 35,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 36,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 37,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 38,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 39,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 40,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 41,
        size: "lg",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 42,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 43,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 44,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 45,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 46,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
      {
        id: 47,
        size: "xl",
        locked: true,
        occupied: false,
        selected: false,
      },
    ],
  },
  mutations: {
    setLockers(state, lockers) {
      state.lockers = lockers;
    },
  },
  actions: {
    setLockers(context, lockers) {
      context.commit("setLockers", lockers);
    },
  },

  getters: {
    getLockers: (state) => {
      return state.lockers;
    },
  },
};

export default lockers;
